const TestDataFileCities = [  
  {
    id: 21307,
    name: "Scaramouche Restaurant",
    address: "1 Benvenuto Place",
    city: "Toronto",
    state: "ON",
    area: "Toronto / SW Ontario",
    postal_code: "M4V 2L1",
    country: "CA",
    phone: "4169618011",
    lat: 43.68207,
    lng: -79.40041,
    price: 4,
    reserve_url: "http://www.opentable.com/single.aspx?rid=21307",
    mobile_reserve_url: "http://mobile.opentable.com/opentable/?restId=21307",
    image_url: "https://www.opentable.com/img/restimages/21307.jpg"
    },
    {
    id: 82957,
    name: "The Sultan's Tent",
    address: "49 Front St E",
    city: "Toronto",
    state: "ON",
    area: "Toronto / SW Ontario",
    postal_code: "M5E 1B3",
    country: "CA",
    phone: "4169610601x",
    lat: 43.648033,
    lng: -79.374377,
    price: 4,
    reserve_url: "http://www.opentable.com/single.aspx?rid=82957",
    mobile_reserve_url: "http://mobile.opentable.com/opentable/?restId=82957",
    image_url: "https://www.opentable.com/img/restimages/82957.jpg"
    },
    {
      id: 4162,
      name: "Orsay",
      address: "1057-59 Lexington Avenue",
      city: "New York",
      state: "NY",
      area: "New York / Tri-State Area",
      postal_code: "10021",
      country: "US",
      phone: "2125176400x0",
      lat: 40.772397,
      lng: -73.960762,
      price: 3,
      reserve_url: "http://www.opentable.com/single.aspx?rid=4162",
      mobile_reserve_url: "http://mobile.opentable.com/opentable/?restId=4162",
      image_url: "https://www.opentable.com/img/restimages/4162.jpg"
      },
      {
      id: 24202,
      name: "Hill Country - Flatiron",
      address: "30 West 26th Street",
      city: "New York",
      state: "NY",
      area: "New York / Tri-State Area",
      postal_code: "10010",
      country: "US",
      phone: "2122554544x10",
      lat: 40.744163,
      lng: -73.990471,
      price: 2,
      reserve_url: "http://www.opentable.com/single.aspx?rid=24202",
      mobile_reserve_url: "http://mobile.opentable.com/opentable/?restId=24202",
      image_url: "https://www.opentable.com/img/restimages/24202.jpg"
      }
]

export default TestDataFileCities